=== unflesed/Web_Services_1/src/practise/planes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="planes" type="planesType"/>
  <xs:complexType name="CharsType">
    <xs:sequence>
      <xs:element name="type">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="passenger"/>
            <xs:enumeration value="agricultural"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="crew">
        <xs:simpleType>
          <xs:restriction base="xs:byte">
            <xs:enumeration value="7"/>
            <xs:enumeration value="1"/>
            <xs:enumeration value="6"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="characteristics">
        <xs:simpleType>
          <xs:restriction base="xs:short">
            <xs:enumeration value="200"/>
            <xs:enumeration value="3"/>
            <xs:enumeration value="220"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="radar">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="true"/>
            <xs:enumeration value="false"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="parametersType">
    <xs:sequence>
      <xs:element name="length">
        <xs:simpleType>
          <xs:restriction base="xs:byte">
            <xs:enumeration value="50"/>
            <xs:enumeration value="10"/>
            <xs:enumeration value="60"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="width">
        <xs:simpleType>
          <xs:restriction base="xs:byte">
            <xs:enumeration value="30"/>
            <xs:enumeration value="5"/>
            <xs:enumeration value="35"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="height">
        <xs:simpleType>
          <xs:restriction base="xs:byte">
            <xs:enumeration value="5"/>
            <xs:enumeration value="3"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="priceType">
    <xs:simpleContent>
      <xs:extension base="xs:int">
        <xs:attribute type="xs:string" name="currency" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="planeType">
    <xs:sequence>
      <xs:element name="model">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Boeing 747"/>
            <xs:enumeration value="Kukuruznik"/>
            <xs:enumeration value="AirBus"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="origin">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="USA"/>
            <xs:enumeration value="USSR"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element type="CharsType" name="Chars"/>
      <xs:element type="parametersType" name="parameters"/>
      <xs:element type="priceType" name="price"/>
    </xs:sequence>
    <xs:attribute type="xs:long" name="id" use="optional"/>
  </xs:complexType>
  <xs:complexType name="planesType">
    <xs:sequence>
      <xs:element type="planeType" name="plane" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== unflesed/Web_Services_1/src/practice/planes.xml
<?xml version="1.0" encoding="UTF-8" ?>

<planes xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation = "planes.xsd">
    <plane id = "1">
        <model>Boeing 747</model>
        <origin>USA</origin>
        <Chars>
            <type>passenger</type>
            <crew>7</crew>
            <characteristics>200</characteristics>
            <radar>true</radar>
        </Chars>
        <parameters>
            <length>50</length>
            <width>30</width>
            <height>5</height>
        </parameters>
        <price currency = "T">1000000</price>
    </plane>
    <plane id = "2">
        <model>Kukuruznik</model>
        <origin>USSR</origin>
        <Chars>
            <type>agricultural</type>
            <crew>1</crew>
            <characteristics>3</characteristics>
            <radar>false</radar>
        </Chars>
        <parameters>
            <length>10</length>
            <width>5</width>
            <height>3</height>
        </parameters>
        <price currency = "T">10000</price>
    </plane>
    <plane id = "3">
        <model>AirBus</model>
        <origin>USA</origin>
        <Chars>
            <type>passenger</type>
            <crew>6</crew>
            <characteristics>220</characteristics>
            <radar>true</radar>
        </Chars>
        <parameters>
            <length>60</length>
            <width>35</width>
            <height>5</height>
        </parameters>
        <price currency = "T">1100000</price>
    </plane>
</planes>
